from_latest_tag = true
ignore_merge_commits = true
tag_prefix = "v"

pre_bump_hooks = [
  "uv version {{version}}",
  "uv lock --check",
  "uv build",
  "git add :/pyproject.toml :/uv.lock",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "rtuszik"
repository = "woodpecker-mcp"
